### ISSUE TITLE
Новый топик для dump

### ISSUE THREAD

**Issue by Snake5932** [Snake5932/ecp32-streamer#7]
Необходимо публиковать дамп камеры не в общем топике data, а в отдельном топике dump. Сообщения qos 0 без retained

**Comment by Snake5932** [comment]
Наверное надо будет qos все таки на 2 поставить

**Comment by Snake5932** [comment]
@frussian, qos на 2 поставил?

**Comment by frussian** [comment]
> @frussian, qos на 2 поставил?

Так точно
